services:
  ravendb1:
    container_name: ravendb1
    image: ravendb/ravendb
    ports:
      - 8081:8080
      - 38889:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_SETTINGS={}
      - "RAVEN_PublicServerUrl=http://ravendb1:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://ravendb1:38888"
    restart: always
    
  ravendb2:
    container_name: ravendb2
    image: ravendb/ravendb
    ports:
      - 8082:8080
      - 38882:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_SETTINGS={}
      - "RAVEN_PublicServerUrl=http://ravendb2:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://ravendb2:38888"
    restart: always
    
  ravendb3:
    container_name: ravendb3
    image: ravendb/ravendb
    ports:
      - 8083:8080
      - 38883:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_SETTINGS={}
      - "RAVEN_PublicServerUrl=http://ravendb3:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://ravendb3:38888"
    restart: always
      
  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "AkkaTrader"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"

  tradeprocessor:
    image: akka.cqrs.tradeprocessor
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      RAVENDB_URL: "http://ravendb1:8080"
      RAVENDB_NAME: "AkkaStorage"
    restart: on-failure
    depends_on:
      - "ravendb1"
      - "ravendb2"
      - "ravendb3"
      - "lighthouse"

  traders:
    image: akka.cqrs.traders
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  lighthouse_pricing:
    image: petabridge/lighthouse:latest
    hostname: lighthouse_pricing
    ports:
      - '9111:9110'
      - '4054:4054'
    environment:
      ACTORSYSTEM: "AkkaPricing"
      CLUSTER_PORT: 4054
      CLUSTER_IP: "lighthouse_pricing"
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"

  pricing-engine:
    image: akka.cqrs.pricing
    deploy:
      replicas: 3
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"
      CLUSTER_PORT: 6055
      RAVENDB_URL: "http://ravendb1:8080"
      RAVENDB_NAME: "AkkaStorage"
    restart: on-failure
    depends_on:
      - "ravendb1"
      - "ravendb2"
      - "ravendb3"
      - "lighthouse_pricing"